apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: teleportal-app
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: teleportal
data:
  TELEPORTAL_APP_NAME: "notification-service"
  TELEPORTAL_LOG_LEVEL: "INFO"
  TELEPORTAL_RABBITMQ_URL: "amqp://guest:guest@rabbitmq.teleportal-infra.svc.cluster.local:5672/"
