apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secrets
  namespace: teleportal-app
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: teleportal
type: Opaque
stringData:
  TELEPORTAL_DATABASE_URL: "postgresql+asyncpg://teleportal:teleportal-demo@notification-db.teleportal-infra.svc.cluster.local:5432/notifications"
