apiVersion: v1
kind: ConfigMap
metadata:
  name: usage-service-config
  namespace: teleportal-app
  labels:
    app.kubernetes.io/name: usage-service
    app.kubernetes.io/part-of: teleportal
data:
  TELEPORTAL_APP_NAME: "usage-service"
  TELEPORTAL_LOG_LEVEL: "INFO"
  TELEPORTAL_REDIS_URL: "redis://redis.teleportal-infra.svc.cluster.local:6379/0"
  TELEPORTAL_RABBITMQ_URL: "amqp://guest:guest@rabbitmq.teleportal-infra.svc.cluster.local:5672/"
