apiVersion: v1
kind: ConfigMap
metadata:
  name: subscriber-service-config
  namespace: teleportal-app
  labels:
    app.kubernetes.io/name: subscriber-service
    app.kubernetes.io/part-of: teleportal
data:
  TELEPORTAL_APP_NAME: "subscriber-service"
  TELEPORTAL_LOG_LEVEL: "INFO"
  TELEPORTAL_PLAN_SERVICE_URL: "http://plan-service.teleportal-app.svc.cluster.local:8000"
  TELEPORTAL_RABBITMQ_URL: "amqp://guest:guest@rabbitmq.teleportal-infra.svc.cluster.local:5672/"
