apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: api-gateway
  namespace: teleportal-app
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: teleportal
spec:
  source:
    type: Git
    git:
      uri: https://github.com/AltintasMehmet/RHACM.git
      ref: main
    contextDir: services/api-gateway
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: api-gateway:latest
  triggers:
    - type: ConfigChange
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: subscriber-service
  namespace: teleportal-app
  labels:
    app.kubernetes.io/name: subscriber-service
    app.kubernetes.io/part-of: teleportal
spec:
  source:
    type: Git
    git:
      uri: https://github.com/AltintasMehmet/RHACM.git
      ref: main
    contextDir: services/subscriber-service
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: subscriber-service:latest
  triggers:
    - type: ConfigChange
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: plan-service
  namespace: teleportal-app
  labels:
    app.kubernetes.io/name: plan-service
    app.kubernetes.io/part-of: teleportal
spec:
  source:
    type: Git
    git:
      uri: https://github.com/AltintasMehmet/RHACM.git
      ref: main
    contextDir: services/plan-service
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: plan-service:latest
  triggers:
    - type: ConfigChange
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: usage-service
  namespace: teleportal-app
  labels:
    app.kubernetes.io/name: usage-service
    app.kubernetes.io/part-of: teleportal
spec:
  source:
    type: Git
    git:
      uri: https://github.com/AltintasMehmet/RHACM.git
      ref: main
    contextDir: services/usage-service
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: usage-service:latest
  triggers:
    - type: ConfigChange
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: billing-service
  namespace: teleportal-app
  labels:
    app.kubernetes.io/name: billing-service
    app.kubernetes.io/part-of: teleportal
spec:
  source:
    type: Git
    git:
      uri: https://github.com/AltintasMehmet/RHACM.git
      ref: main
    contextDir: services/billing-service
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: billing-service:latest
  triggers:
    - type: ConfigChange
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: notification-service
  namespace: teleportal-app
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: teleportal
spec:
  source:
    type: Git
    git:
      uri: https://github.com/AltintasMehmet/RHACM.git
      ref: main
    contextDir: services/notification-service
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: notification-service:latest
  triggers:
    - type: ConfigChange
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: network-status-service
  namespace: teleportal-app
  labels:
    app.kubernetes.io/name: network-status-service
    app.kubernetes.io/part-of: teleportal
spec:
  source:
    type: Git
    git:
      uri: https://github.com/AltintasMehmet/RHACM.git
      ref: main
    contextDir: services/network-status-service
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: network-status-service:latest
  triggers:
    - type: ConfigChange
