apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: api-gateway
  namespace: teleportal-app
  labels:
    app.kubernetes.io/part-of: teleportal
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: subscriber-service
  namespace: teleportal-app
  labels:
    app.kubernetes.io/part-of: teleportal
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: plan-service
  namespace: teleportal-app
  labels:
    app.kubernetes.io/part-of: teleportal
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: usage-service
  namespace: teleportal-app
  labels:
    app.kubernetes.io/part-of: teleportal
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: billing-service
  namespace: teleportal-app
  labels:
    app.kubernetes.io/part-of: teleportal
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: notification-service
  namespace: teleportal-app
  labels:
    app.kubernetes.io/part-of: teleportal
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: network-status-service
  namespace: teleportal-app
  labels:
    app.kubernetes.io/part-of: teleportal
spec:
  lookupPolicy:
    local: true
