apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: teleportal-infra
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: teleportal
    app.kubernetes.io/component: infrastructure
type: Opaque
stringData:
  POSTGRES_PASSWORD: "teleportal-demo"
