apiVersion: v1
kind: ConfigMap
metadata:
  name: plan-service-config
  namespace: teleportal-app
  labels:
    app.kubernetes.io/name: plan-service
    app.kubernetes.io/part-of: teleportal
data:
  TELEPORTAL_APP_NAME: "plan-service"
  TELEPORTAL_LOG_LEVEL: "INFO"
