apiVersion: v1
kind: Service
metadata:
  name: plan-service
  namespace: teleportal-app
  labels:
    app.kubernetes.io/name: plan-service
    app.kubernetes.io/part-of: teleportal
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: plan-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
