apiVersion: v1
kind: Secret
metadata:
  name: billing-service-secrets
  namespace: teleportal-app
  labels:
    app.kubernetes.io/name: billing-service
    app.kubernetes.io/part-of: teleportal
type: Opaque
stringData:
  TELEPORTAL_DATABASE_URL: "postgresql+asyncpg://teleportal:teleportal-demo@billing-db.teleportal-infra.svc.cluster.local:5432/billing"
