apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-teleportal-certificate
  namespace: teleportal-app
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/controls: SC-12 Cryptographic Key Establishment and Management
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: CertificatePolicy
        metadata:
          name: teleportal-certificate-expiry
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            include:
              - teleportal-app
          minimumDuration: 720h
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-certificate
  namespace: teleportal-app
spec:
  clusterSets:
    - telenet-production
    - telenet-staging
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-certificate
  namespace: teleportal-app
spec:
  placementRef:
    name: placement-policy-certificate
    kind: Placement
    apiGroup: cluster.open-cluster-management.io
  subjects:
    - name: policy-teleportal-certificate
      kind: Policy
      apiGroup: policy.open-cluster-management.io
