apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rabbitmq-allow-ingress
  namespace: teleportal-infra
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: teleportal
    app.kubernetes.io/component: infrastructure
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/part-of: teleportal
          podSelector:
            matchLabels:
              app.kubernetes.io/name: subscriber-service
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/part-of: teleportal
          podSelector:
            matchLabels:
              app.kubernetes.io/name: usage-service
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/part-of: teleportal
          podSelector:
            matchLabels:
              app.kubernetes.io/name: billing-service
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/part-of: teleportal
          podSelector:
            matchLabels:
              app.kubernetes.io/name: notification-service
      ports:
        - protocol: TCP
          port: 5672
