apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: teleportal
  namespace: teleportal-app
  labels:
    app.kubernetes.io/part-of: teleportal
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchLabels:
      app.kubernetes.io/part-of: teleportal
