apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: teleportal-git
  namespace: teleportal-app
  labels:
    app.kubernetes.io/part-of: teleportal
spec:
  type: Git
  pathname: https://github.com/AltintasMehmet/public.git
