# Dev patches - set all deployments to 1 replica
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: teleportal-app
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber-service
  namespace: teleportal-app
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plan-service
  namespace: teleportal-app
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usage-service
  namespace: teleportal-app
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: teleportal-app
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: teleportal-app
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-status-service
  namespace: teleportal-app
spec:
  replicas: 1
